document.addEventListener('DOMContentLoaded', () => {
    // Baza danych w postaci tablicy w JavaScript
    const words = [
        { polish: "nazwa, nazwisko", english: "name (nejm)" },
        { polish: "bardzo", english: "very (weri)" },
        { polish: "do,ku,na,po,za,dla,przy,aby,żeby", english: "to (tu)" },
        { polish: "przez,poprzez", english: "through (fru)" },
        { polish: "i", english: "and (end)" },
        { polish: "tylko,właśnie", english: "just (dżast)" },
        { polish: "forma,tworzyć", english: "form (form)" },
        { polish: "w", english: "in (yn)" },
        { polish: "zdanie", english: "sentence (sentens)" },
        { polish: "it", english: "to (yt)" },
        { polish: "świetnie", english: "great (grejt)" },
        { polish: "myśleć,uważać", english: "think (fynk)" },
        { polish: "mówić,powiedzieć", english: "say (sej)" },
        { polish: "że,ten,tamten,to,który", english: "that (wet)" },
	{ polish: "pomoc,pomagać", english: "help (help" },
	{ polish: "niski,cichy,nisko,cicho,przygnębiony", english: "low (loł)" },
	{ polish: "linia,lina,kolejka,rząd", english: "line (lajn)" },
	{ polish: "dla,do,po", english: "for (for)" },
	{ polish: "różnić się", english: "differ (dyfer)" },
	{ polish: "na", english: "on (on)" },
	{ polish: "skręcić,zakręt,obrót", english: "turn (tern)" },
	{ polish: "przyczyna,powód,pot.ponieważ", english: "cause (koz)" },
	{ polish: "z", english: "with (łyf)" },
	{ polish: "dużo", english: "much (macz)" },
	{ polish: "kiedy,gdy,ponieważ,tak jak", english: "as (ez)" },
	{ polish: "znaczyć,skąpy,złośliwy,średni", english: "mean (min)" },
	{ polish: "przed", english: "before (bifor)" },
	{ polish: "jego", english: "his (hys)" },
	{ polish: "ruszać,ruch", english: "move (muw)" },
	{ polish: "oni", english: "they (wej)" },
	{ polish: "prawy,poprawny,dobry", english: "right (rajt)" },
	{ polish: "być", english: "be (bi)" },
	{ polish: "chłopiec", english: "boy (boj)" },
	{ polish: "przy,w,o,na", english: "at (et)" },
	{ polish: "stary", english: "old (old)" },
	{ polish: "jeden", english: "one (łan)" },
	{ polish: "także,za", english: "too (tu)" },
	{ polish: "mieć", english: "have (hew)" },
	{ polish: "ten sam,taki sam", english: "same (sejm)" },
	{ polish: "ten,ta", english: "this (dys)" },
	{ polish: "powiedzieć", english: "tell (tel)" },
	{ polish: "od,z", english: "from (from)" },
	{ polish: "albo", english: "or (or)" },
	{ polish: "komplet,grupa", english: "set (set)" },
	{ polish: "trzy", english: "three (fri)" },
	{ polish: "przez", english: "by (baj)" },
	{ polish: "chcieć", english: "want (łont)" },
	{ polish: "gorący", english: "hot (hot)" },
	{ polish: "powietrze", english: "air (er)" },
	{ polish: "słowo", english: "word (łerd)" },
	{ polish: "cóż,dobrze", english: "well (łel)" },
	{ polish: "ale", english: "but (bat)" },
	{ polish: "także", english: "also (olso)" },
	{ polish: "co", english: "what (łot)" },
	{ polish: "grać,gra", english: "play (plej)" },
	{ polish: "kilka,niektóre", english: "some (sam)" },
	{ polish: "małe", english: "small (smol" },
	{ polish: "konic, kończyć", english: "end (end)" },
	{ polish: "umieć,potrafić", english: "can (ken)" },
	{ polish: "na zewnątrz", english: "out (ałt)" },
	{ polish: "dom", english: "home (hołm)" },
	{ polish: "inne", english: "other (awer)" },
	{ polish: "czytać", english: "read (rid)" },
	{ polish: "byli,byłeś", english: "were (łer)" },
	{ polish: "dłoń", english: "hand (hend)" },
	{ polish: "wszystko", english: "all (ol)" },
	{ polish: "port", english: "port (port)" },
	{ polish: "tam", english: "there (wer)" },
	{ polish: "olbrzymi", english: "large (lardż)" },
	{ polish: "kiedy,gdy", english: "when (łen)" },
	{ polish: "literować,zaklęcie", english: "spell (spel)" },
	{ polish: "na górę", english: "up (ap)" },
	{ polish: "dodać", english: "add (ed)" },
	{ polish: "używać,użyć", english: "use (juz)" },
	{ polish: "nawet,równy", english: "even (iwen)" },
	{ polish: "twój", english: "your (jor)" },
	{ polish: "ziemia,lądować", english: "land (lend)" },
	{ polish: "jak", english: "how (hał)" },
	{ polish: "tutaj", english: "here (hir)" },
	{ polish: "powiedział", english: "said (sed)" },
	{ polish: "musieć", english: "must (mast)" },
	{ polish: "duży", english: "big (byg)" },
	{ polish: "każdy", english: "each (icz)" },
	{ polish: "wysoki,wysoko", english: "high (haj" },
	{ polish: "ona", english: "she (szi)" },
	{ polish: "taki", english: "such (sacz)" },
	{ polish: "któryy", english: "which (łicz)" },
	{ polish: "stosować się,iść za,śledzić", english: "follow (foloł)" },
	{ polish: "robić, operator PSimple", english: "do (du)" },
	{ polish: "działać,ustawa", english: "act (akt)" },
	{ polish: "ich", english: "their (weir)" },
	{ polish: "dlaczego", english: "why (łaj)" },
	{ polish: "czas", english: "time (tajm)" },
	{ polish: "pytać", english: "ask (ask)" },
	{ polish: "jeśli", english: "if (yf)" },
	{ polish: "mężczyzna,człowiek", english: "men (men)" },
	{ polish: "będzie", english: "will (łyl)" },
	{ polish: "zmiana,zmieniać", english: "change (czeńdż)" },
	{ polish: "sposób,droga", english: "way (łej)" },
	{ polish: "poszedł,poszli", english: "went (łent)" },
	{ polish: "o,około", english: "about (ebałt)" },
	{ polish: "światło,zapalać,jasny,lekki", english: "light (lajt)" },
	{ polish: "wiele,dużo", english: "many (meny)" },
	{ polish: "rodzaj", english: "kind (kajnd)" },
	{ polish: "potem,wtedy", english: "then (wen)" },
	{ polish: "ich", english: "them (wem)" },
	{ polish: "potrzebować,potrzeba", english: "need (nid)" },
	{ polish: "pisać", english: "write (rajt)" },
	{ polish: "dom", english: "house (hałs)" },
	{ polish: "zrobiłbym,dałbym", english: "would (łud)" },
	{ polish: "obraz,wyobrażać", english: "picture (pikczer)" },
	{ polish: "lubić,jak", english: "like (lajk)" },
	{ polish: "próbować", english: "try (traj)" },
	{ polish: "więć,taki", english: "so (soł)" },
	{ polish: "nas", english: "us (as)" },
	{ polish: "te", english: "these (diz)" },
	{ polish: "znowu", english: "again (egejn)" },
	{ polish: "zwierze", english: "animal (enymal)" },
	{ polish: "długi", english: "long (long)" },	
	{ polish: "punkt,wskazywać", english: "point (pojnt)" },
	{ polish: "robić", english: "make (mejk)" },
	{ polish: "mama", english: "mother (mawer)" },
	{ polish: "rzecz", english: "thing (fyng)" },
	{ polish: "świat", english: "world (łerld)" },
	{ polish: "widzieć", english: "see (si)" },
	{ polish: "blisko,obok", english: "near (nir)" },
	{ polish: "jego", english: "him (hym)" },
	{ polish: "budować", english: "build (byld)" },
	{ polish: "dwa", english: "two (tu)" },
	{ polish: "swoje,sobie,ja", english: "self (self)" },
	{ polish: "ziemia", english: "earth (erf)" },
	{ polish: "patrzeć,wyglądać", english: "look (luk)" },
	{ polish: "ojciec", english: "father (fawer)" },
	{ polish: "więcej", english: "more (mor)" },
	{ polish: "głowa, główny", english: "head (hed)" },
	{ polish: "dzień", english: "day (dej)" },
	{ polish: "stać,stoisko", english: "stand (stend)" },
	{ polish: "móc", english: "could (kud)" },
	{ polish: "posiadać,własny", english: "own (ołn)" },
	{ polish: "iść", english: "go (goł)" },
	{ polish: "przychodzić,przyjedżać", english: "come (kam)" },
	{ polish: "powinien", english: "should (szud)" },
	{ polish: "robił, operator PastSimple", english: "did (dyd)" },
	{ polish: "państwo,wieś", english: "country (kantry)" },
	{ polish: "liczba,numer,wiele", english: "number (namber)" },
	{ polish: "znalezione,znalazł", english: "found (fałnd)" },
	{ polish: "dźwięk,brzmieć", english: "sound (sałnd)" },
	{ polish: "odpowiedź,odpowiadać", english: "answer (anser)" },
	{ polish: "nie,żadnych", english: "no (noł)" },
	{ polish: "szkoła", english: "school (skul)" },
	{ polish: "najwięcej", english: "most (mołst)" },
	{ polish: "rosnąć", english: "grow (groł)" },
	{ polish: "ludzie", english: "people (pipol)" },
	{ polish: "studiować,uczyć się", english: "study (stadi)" },
	{ polish: "moje", english: "my (maj)" },
	{ polish: "ciągle", english: "still (styl)" },
	{ polish: "nad,przez", english: "over (ołwer)" },
	{ polish: "uczyć się", english: "learn (lern)" },
	{ polish: "wiedzić,znać", english: "known (noł)" },
	{ polish: "roślina,fabryka,sadzić", english: "plant (plant)" },
	{ polish: "woda,podlewać", english: "water (łoter)" },
	{ polish: "okładka,przykrywać", english: "cover (kawer)" },
	{ polish: "niż", english: "than (wen)" },
	{ polish: "jedzenie,pokarm", english: "food (fud)" },
	{ polish: "dzwonić,nazywać,rozmowa tel", english: "call (kol)" },
	{ polish: "słońce", english: "sun (san)" },
	{ polish: "pierwszy", english: "first (ferst)" },
	{ polish: "cztery", english: "four (for)" },
	{ polish: "kto,który", english: "who (hu)" },
	{ polish: "pomiędzy", english: "between (bitłin)" },
	{ polish: "móc", english: "may (mej)" },
	{ polish: "stan,państwo,oświadczać", english: "state (stejt)" },
	{ polish: "w dół", english: "down (dałn)" },
	{ polish: "trzymać,zachowywać coś", english: "keep (kip)" },
	{ polish: "strona", english: "side sajd)" },
	{ polish: "oko", english: "eye (aj)" },
	{ polish: "nigdy", english: "never (newer)" },
	{ polish: "teraz", english: "now (nał)" },
	{ polish: "ostatni", english: "last (last)" },
	{ polish: "znaleźć,uważać za", english: "find (fajnd)" },
	{ polish: "pozwolić,wynajmować", english: "let (let)" },
	{ polish: "jakikolwiek,jakieś,żadne", english: "any (eny)" },
	{ polish: "myśl,myśleć w czasi przeszłym", english: "thought (fot)" },
	{ polish: "nowy", english: "new (nju)" },
	{ polish: "miasto", english: "city (siti)" },
	{ polish: "praca,pracować", english: "work (łork)" },
	{ polish: "drzewo", english: "tree (tri)" },
	{ polish: "część", english: "part (part)" },
	{ polish: "krzyż,przechodzić przez", english: "cross (kros)" },
	{ polish: "wziąć", english: "take (tejk)" },
	{ polish: "gospodarstwo,uprawiać", english: "farm (farm)" },
	{ polish: "dostać", english: "get (get)" },
	{ polish: "twardy,trudny", english: "hard (hard)" },
	{ polish: "miejsce", english: "place (plejs)" },
	{ polish: "zacynać", english: "start (start)" },
	{ polish: "zrobione,robić w czasie przeszłym", english: "made" },
	{ polish: "móc", english: "might (majt)" },
	{ polish: "mieszkać,żyć", english: "live (lyw)" },
	{ polish: "opowiadanie,historia", english: "story (story)" },
	{ polish: "gdzie", english: "where (łer" },
	{ polish: "widzieć w czasie przeszłym", english: "saw (so)" },
	{ polish: "po", english: "after (after)" },
	{ polish: "daleko", english: "far (far)" },
	{ polish: "z powrotem,plecy", english: "back (bek)" },
	{ polish: "morze", english: "sea (si)" },
	{ polish: "mało,mały", english: "little (lytyl)" },
	{ polish: "rysować", english: "draw (dro)" },
	{ polish: "tylko", english: "only (onli)" },
	{ polish: "lewy,pozostawiony", english: "left (left)" },
	{ polish: "okrągły,okrążać,w kółko,runda", english: "around (rałnd)" },
	{ polish: "późno", english: "late (lejt)" },
	{ polish: "człowiek,mężczyźni", english: "man (men)" },
	{ polish: "biegać", english: "run (ran)" },
	
	    
    ];

    // Funkcja do losowania unikalnych słów
    function getRandomWords(wordsArray, count) {
        const result = [];
        const availableIndexes = [...Array(wordsArray.length).keys()]; // Tworzymy tablicę indeksów

        for (let i = 0; i < count; i++) {
            // Losujemy indeks
            const randomIndex = Math.floor(Math.random() * availableIndexes.length);
            // Wybieramy słowo z tablicy na podstawie wylosowanego indeksu
            result.push(wordsArray[availableIndexes[randomIndex]]);
            // Usuwamy ten indeks, aby się nie powtórzył
            availableIndexes.splice(randomIndex, 1);
        }

        return result;
    }

    // Wyciągamy 10 losowych słów
    const randomWords = getRandomWords(words, 10);

    // Tworzymy listę słówek na podstawie losowej selekcji
    const wordList = document.querySelector('.word-list');
    randomWords.forEach(word => {
        const wordElement = document.createElement('div');
        wordElement.classList.add('word');
        wordElement.setAttribute('data-translation', word.english);
        wordElement.textContent = word.polish;
        wordList.appendChild(wordElement);
    });
    // Funkcja do odświeżania strony po kliknięciu przycisku
    const refreshButton = document.getElementById('refresh-button');
    refreshButton.addEventListener('click', () => {
        location.reload(); // Odśwież stronę
    });
});
